variables:
  DOCKER_DRIVER: overlay2
  # Nome da imagem que será gerada. Mantenha consistente.
  IMAGE_NAME: timesheet-api

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:24.0.9
  services:
    - name: docker:24.0.9-dind
  only:
    - main # Ou a branch que você usa para deploy
  script:
    - echo "nameserver 192.168.1.8" | tee /etc/resolv.conf
    - docker login "$REGISTRY_ADDRESS" --username "$REGISTRY_USERNAME" --password "$REGISTRY_PASSWORD"
    - docker build -t "$REGISTRY_ADDRESS/$IMAGE_NAME:latest" .
    - docker push "$REGISTRY_ADDRESS/$IMAGE_NAME:latest"

deploy:
  stage: deploy
  only: 
    - main # Ou a branch que você usa para deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    # ⚠️ ATENÇÃO: Substitua os valores abaixo pelos nomes corretos do seu ambiente no Rancher
    - upgrade --environment "Default" --stack "Controle-Demandas" --service "timesheet-api" --new-image "$REGISTRY_ADDRESS/$IMAGE_NAME:latest"