variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: timesheet-api 

stages:
  - build
  - deploy

build:
  image: docker:24.0.9
  services:
    - name: docker:24.0.9-dind
  stage: build
  only:
    - main
  script:  
    - echo "nameserver 192.168.1.8" | tee /etc/resolv.conf
    - docker login "$REGISTRY_ADDRESS" --username "$REGISTRY_USERNAME" --password "$REGISTRY_PASSWORD"    
    - docker build -t "$REGISTRY_ADDRESS/$IMAGE_NAME:latest" .
    - docker push "$REGISTRY_ADDRESS/$IMAGE_NAME:latest"

deploy:
  stage: deploy
  image: rancher/cli:v0.6.14
  script:
    - rancher --url "$RANCHER_URL" --access-key "$RANCHER_ACCESS_KEY" --secret-key "$RANCHER_SECRET_KEY" \
      up -d --stack Controle-Demandas --file docker-compose.yml --confirm-upgrade --force-upgrade

